"""optional param to facilities in rooms

Revision ID: ffa86ed02d20
Revises: 69258520ff95
Create Date: 2025-02-11 15:09:25.208070

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffa86ed02d20"
down_revision: Union[str, None] = "69258520ff95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rooms_facilities",
        "room_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "rooms_facilities",
        "facility_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rooms_facilities",
        "facility_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "rooms_facilities",
        "room_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
