repos:
  - repo: local
    hooks:
    - id: ruff
      name: ruff
      entry: poetry run ruff checks
      language: system
      types: [python]
      stages: [pre-commit]

    # - id: black
    #   name: black
    #   entry: poetry run black
    #   language: system
    #   types: [python]
    #   stages: [pre-commit]
    #   args: [--line-length=70, --target-version=py311]

    # - id: autopep8
    #   name: autopep8
    #   entry: poetry run autopep8
    #   language: system
    #   types: [python]
    #   stages: [pre-commit]
    #   args: [--in-place, --max-line-length=79] 

    # - id: autoflake
    #   name: autoflake
    #   entry: poetry run autoflake
    #   language: system
    #   types: [python]
    #   stages: [pre-commit]
    #   args: [--in-place, --remove-all-unused-imports, --remove-unused-variables,  --remove-duplicate-keys]

    # - id: pyupgrade
    #   name: pyupgrade
    #   entry: poetry run pyupgrade
    #   language: system
    #   types: [python]
    #   stages: [pre-push]
    #   args: [--py37-plus]

    # - id: yesqa
    #   name: yesqa
    #   entry: poetry run yesqa
    #   language: system
    #   stages: [pre-push]
    #   types: [python]
  