

repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: poetry run black
      language: system
      types: [python]
      stages: [pre-commit]
      args: [--line-length=70, --target-version=py311]

    - id: autoflake
      name: autoflake
      entry: poetry run autoflake
      language: system
      types: [python]
      stages: [pre-commit]
      args: [--in-place, --remove-all-unused-imports, --remove-unused-variables,  --remove-duplicate-keys]

    # - id: flake8
    #   name: flake8
    #   entry: poetry run flake8
    #   language: system
    #   types: [python]
    #   stages: [pre-push]
    #   args: ["--ignore=W191,E12"]

    - id: pyupgrade
      name: pyupgrade
      entry: poetry run pyupgrade
      language: system
      types: [python]
      stages: [pre-push]
      args: [--py37-plus]

    - id: yesqa
      name: yesqa
      entry: poetry run yesqa
      language: system
      stages: [pre-push]
      types: [python]

    # - id: mypy
    #   name: mypy
    #   entry: poetry run mypy
    #   language: system
    #   stages: [pre-push]
    #   types: [python]
    
    # - id: pylint
    #   name: pylint
    #   entry: poetry run pylint
    #   language: system
    #   stages: [pre-push]
    #   types: [python]
    #   args: ["--max-line-length=120"]  